version: '3.8'

services:
  # LocalStack Community Edition - Free services only (Lambda, S3, CloudWatch Logs)
  localstack:
    image: localstack/localstack:latest
    container_name: lark-connector-localstack
    ports:
      - "4566:4566"  # LocalStack Gateway
      - "4571:4571"  # LocalStack internal
    environment:
      # Only use services available in Community Edition
      - SERVICES=lambda,s3,logs,sts,iam
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker-reuse
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_DOCKER_NETWORK=integration-tests_test-network
      # Performance optimizations
      - LAMBDA_REMOTE_DOCKER=0
      - LAMBDA_REMOVE_CONTAINERS=true
    volumes:
      - "./init-scripts.sh:/etc/localstack/init/ready.d/init-scripts.sh"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # WireMock for mocking Lark API
  wiremock:
    image: wiremock/wiremock:latest
    container_name: lark-api-mock
    ports:
      - "8080:8080"  # WireMock API
    volumes:
      - "../mocks:/home/wiremock"
    command:
      - "--verbose"
      - "--global-response-templating"
      - "--root-dir=/home/wiremock"
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/__admin/health"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  test-network:
    driver: bridge
    name: integration-tests_test-network
